import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

/**
 * Generates a PDF from a DOM element.
 * Optimized for high-quality capture and correct scaling.
 */
export const generateProjectPDF = async (elementId: string, fileName: string) => {
  // Wait slightly for any final renders/animations
  await new Promise(resolve => setTimeout(resolve, 500));

  const element = document.getElementById(elementId);
  if (!element) {
    throw new Error(`Element with id ${elementId} not found`);
  }

  // Create canvas from element with better settings for PDFs
  const canvas = await html2canvas(element, {
    scale: 2, 
    useCORS: true,
    logging: false,
    backgroundColor: '#F8FAFC',
    windowWidth: 1200, // Standardize capture width
    scrollX: 0,
    scrollY: 0,
    onclone: (clonedDoc) => {
      // Optional: hide elements in the clone that shouldn't be in PDF
      const ignoreElements = clonedDoc.querySelectorAll('[data-html2canvas-ignore]');
      ignoreElements.forEach(el => (el as HTMLElement).style.display = 'none');
    }
  });

  const imgData = canvas.toDataURL('image/png', 1.0);
  
  // PDf dimensions in pixels (at 72 DPI)
  const imgWidth = canvas.width / 2;
  const imgHeight = canvas.height / 2;
  
  const pdf = new jsPDF({
    orientation: imgWidth > imgHeight ? 'landscape' : 'portrait',
    unit: 'px',
    format: [imgWidth, imgHeight]
  });

  pdf.addImage(imgData, 'PNG', 0, 0, imgWidth, imgHeight, undefined, 'FAST');

  // Add watermarks
  const watermarkText = 'IdeaZen Project Blueprint';
  pdf.setTextColor(200, 201, 202);
  pdf.setFontSize(24);
  
  // Calculate watermark density based on page size
  const stepX = 250;
  const stepY = 350;
  
  for (let x = 50; x < imgWidth; x += stepX) {
    for (let y = 100; y < imgHeight; y += stepY) {
      pdf.text(watermarkText, x, y, { 
        angle: 45
      });
    }
  }

  // Add Branding Footer
  pdf.setFontSize(12);
  pdf.setTextColor(100, 116, 139); // Slate-500
  pdf.text('Generated by IdeaZen - Your AI Project Architect', 30, imgHeight - 30);
  pdf.text('ideazen.io', imgWidth - 80, imgHeight - 30);

  pdf.save(`${fileName.replace(/\s+/g, '_').toLowerCase()}_blueprint.pdf`);
};
